### ISSUE TITLE
aliases for the search

### ISSUE THREAD

**Issue by norbu09** [grantm/ucf#1]
the term "umlaut" is pretty much standard for (at least) german diaeresis (ü, ö, ä) and i always though that the sharp s (ß) is in fact a ligatur - which does not seam so despite the fact that the HTML code i learned for it is '&szlig;'

**Comment by norbu09** [comment]
the '&szlig\;' rendered as a ß ... damn

**Comment by grantm** [comment]
I agree that 'umlaut' is the term people are more likely to be searching for than diaeresis.  At the moment all the character descriptions come straight out of the Unicode data and hence I end up with their terminology.  I do plan to add support for non-official aliases.

**Comment by grantm** [comment]
Finally (5 years later) I got around to implementing an unofficial alias for the umlaut:

http://www.mclean.net.nz/ucf/?q=umlaut

The backend data generator for the Unicode Character fFnder has now been completely rewritten and updated to the latest version of Unicode, but the source data still makes no mention of the term 'umlaut'.
