### ISSUE TITLE
http://www.mclean.net.nz/ucf/ unicode standard is out of date

### ISSUE THREAD

**Issue by douglasbagnall** [grantm/ucf#2]
This is an issue with the reference installation (which I use regularly, thanks!), not with the software itself, though it _could_ be fixed with some kind of auto-update system.

To reproduce:
1. Imagine you are looking for the rewind symbol ⏪, `U+23EA`, also known as “BLACK LEFT-POINTING DOUBLE TRIANGLE”, which arrived in Unicode 6. (ref. 
   http://www.fileformat.info/info/unicode/char/23ea/index.htm).
2. Search for “double triangle” and get no results. Look at the 2380-23ff code page and see an empty square where 23ea would be. Click on the empty square, and see that the character does
   in fact exist (http://www.mclean.net.nz/ucf/?c=U+23EA).
3. Notice that the description is missing.
4. Click on the “prev” and “next” buttons to see if the neighbouring symbols also lack descriptions. Find that the “prev” button takes you to U+23E8 (⏨), not U+23E9 (⏩), and the next button jumps to U+2400 (␀) rather than U+23EB (⏫). It is difficult to navigate the new code regions.

Wikipedia says there is a single new entity in HTML5 but not in XHTML1 (`&vellip;`, ⋮, http://www.mclean.net.nz/ucf/?c=U+22EE), but at the same time HTML5 deprecates the use of
named entities, and the DTD is a `data:` link in the spec, so it might be best to ignore that.

**Comment by grantm** [comment]
I've finally managed to update the Unicode importer script to get the latest data. The character definitions for the code points you listed should all be working now - assuming you're using a font that includes the glyphs.
There are numerous fixes and enhancements that I could/should add, but this one is done 😀
