### ISSUE TITLE
Scratchpad removes characters when switching between text and codepoints

### ISSUE THREAD

**Issue by haydngreatnews** [grantm/ucf#3]
Steps to reproduce:
1. Open scratchpad
2. Set the scratchpad to text mode
3. Paste "ａｅｓ" into the scratchpad (these are full-width latin characters, from the Halfwidth and Fullwidth Forms block)
4. Toggle the scratchpad into codepoint mode
5. Toggle the scratchpad into text mode

At step 4, when switching to codepoint mode, some of the codepoints will not appear in the codepoint view, and do not reappear when switching back to text mode.

This does not appear to happen when using plain ascii text, or when entering characters from the next block (Linear-B syllabary), but the same does seem to happen when entering characters from previous block (Arabic Presentation Forms-B).

Observed on Chromium 52 (whatsmybrowser.org/b/600S8LO)

**Comment by grantm** [comment]
Thanks for the report.

Fix in handling of surrogate pairs is in e2b29e72bf7ecda2a5d3f4c6da500e26e0baf2a2
